# Generated by Django 5.2.6 on 2025-09-10 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FloorState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_code", models.CharField(blank=True, max_length=1, null=True)),
                ("exclude_u", models.CharField(blank=True, max_length=32, null=True)),
                ("exclude_v", models.CharField(blank=True, max_length=32, null=True)),
                ("last_result", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="routing.floor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=32)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="routing.floor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("bidirectional", models.BooleanField(default=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="routing.floor",
                    ),
                ),
                (
                    "u",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges_u",
                        to="routing.node",
                    ),
                ),
                (
                    "v",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges_v",
                        to="routing.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StartNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_nodes",
                        to="routing.floor",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_start",
                        to="routing.node",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["floor", "label"], name="routing_nod_floor_i_648f0d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="node",
            unique_together={("floor", "label")},
        ),
        migrations.AddIndex(
            model_name="startnode",
            index=models.Index(fields=["floor"], name="routing_sta_floor_i_933245_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="startnode",
            unique_together={("floor", "node")},
        ),
    ]
